metno/aerovaldb

setup.cfg
src/aerovaldb/aerovaldb.py
src/aerovaldb/utils.py
tests/test_jsonfiledb.py

This PR allows the getter tasks to be run as methods rather than co-routines if no co-routine-loops exist.
Tests included for both co-routine and method approach.

allowing async functions to be called like synced functions

---

src/aerovaldb/__init__.py
src/aerovaldb/exceptions.py
src/aerovaldb/jsonfiledb.py
src/aerovaldb/types.py
tests/test_jsonfiledb.py

Places aerovaldb wide exceptions and types in `aerovaldb.exceptions` and `aerovaldb.types` respectively for easy importing.

Better exceptions and types

---

setup.cfg
src/aerovaldb/jsondb/jsonfiledb.py
tests/jsondb/test_jsonfiledb.py
tests/test-db/json/project-no-experiments-json/experiment/cfg_project-no-experiments-json_experiment.json
tests/test-db/json/project-no-experiments-json/experiment/contour/modvar_model.geojson
tests/test-db/json/project-no-experiments-json/experiment/contour/obsvar_model.json
tests/test-db/json/project-no-experiments-json/experiment/forecast/region_network-obsvar_layer.json
tests/test-db/json/project-no-experiments-json/experiment/hm/glob_stats_frequency.json
tests/test-db/json/project-no-experiments-json/experiment/hm/ts/_network-obsvar-layer.json
tests/test-db/json/project-no-experiments-json/experiment/hm/ts/region-network-obsvar-layer.json
tests/test-db/json/project-no-experiments-json/experiment/map/network-obsvar_layer_model-modvar_time.json
tests/test-db/json/project-no-experiments-json/experiment/menu.json
tests/test-db/json/project-no-experiments-json/experiment/models-style.json
tests/test-db/json/project-no-experiments-json/experiment/profiles/region_network-obsvar.json
tests/test-db/json/project-no-experiments-json/experiment/ranges.json
tests/test-db/json/project-no-experiments-json/experiment/regions.json
tests/test-db/json/project-no-experiments-json/experiment/scat/network-obsvar_layer_model-modvar_time.json
tests/test-db/json/project-no-experiments-json/experiment/statistics.json
tests/test-db/json/project-no-experiments-json/experiment/ts/diurnal/location_network-obsvar_layer.json
tests/test-db/json/project-no-experiments-json/experiment/ts/location_network-obsvar_layer.json

Small fix to `get_experiments()` that ensures backwards compatibility. `experiments.json` will be read if it exists, but if not it will be generated on the fly.

Small fix to `get_experiments()`

---

README.md
setup.cfg
src/aerovaldb/aerovaldb.py
src/aerovaldb/exceptions.py
src/aerovaldb/jsondb/jsonfiledb.py
src/aerovaldb/routes.py
tests/jsondb/test_jsonfiledb.py

- Implements `list_glob_stats()` which can be used to iterate over all globstats json files.
- Implements `list_map()` which can be used to iterate over all map json files.
- Use `FileNotFoundError` instead of custom exception.
- Reintroduce `put_experiments()`
- Allows specifying a default return value which will be returned instead of raising an exception if no file exists by passing `default = ...` to any get call.
- Refactor to use `get_by_uuid` and `put_by_uuid` in the `_get`/`_put` which should prevent subtle differences in behaviour of eg. caching, and access_mode with different implementations.

A number of fixes

---

docs/index.rst
scripts/aiofile_benchmark.py
setup.cfg
src/aerovaldb/jsondb/cache.py
src/aerovaldb/jsondb/jsonfiledb.py
src/aerovaldb/plugins.py
tests/jsondb/test_jsonfiledb.py

Adds an option to `aerovaldb.open()` to specify whether to read files asynchronously (aiofile) or synchronously.

Add option to toggle async io in open()

---

docs/locking.rst
setup.cfg
src/aerovaldb/jsondb/jsonfiledb.py
src/aerovaldb/lock/lock.py
src/aerovaldb/serialization/default_serialization.py
tests/conftest.py
tests/jsondb/test_lock.py

Implements a number of fixes required for https://github.com/metno/pyaerocom/pull/1273:
- Fixes `TypeError: Type is not JSON serializable: numpy.float64` when serializing numpy floats.
- Fixes dict-key must be str error.
- Aerovaldb defaulting to using the oldest version based filepath template string if cfg file was not written. It will now first try the currently installed version of pyaerocom, if it exists (Needed for files to be written correctly in tests, and other situations where no config file has been written).
- Locking will be enabled based on environment variable `AVDB_USE_LOCKING`. This allows eliminating the performance overhead of locking in context where this is known to be safe (eg. tests or non-parallellized workloads).
https://github.com/metno/pyaerocom/pull/1273

Various fixes required for Pyaerocom writing / locking

---

setup.cfg
src/aerovaldb/__init__.py
src/aerovaldb/plugins.py
tests/test_plugins.py

Allows folder path as resource string to aerovaldb.open().
Tests general parsing of resource string for different cases.
https://github.com/metno/pyaerocom/pull/1273

Allow folder path as resource string

---

setup.cfg
src/aerovaldb/jsondb/jsonfiledb.py
tests/jsondb/test_jsonfiledb.py

Use `ignore_nan=True` when writing json, which writes compliant json and fixes an issue where aeroval-web can't parse generated json.
https://github.com/metno/pyaerocom/issues/1288
This introduces a potential issue in that the data written by aerovaldb will not be the same when read in for nan values. aerovaldb writes nan as null, then reads null as `None` when reading. AFAICT this matches the old behavior of pyaerocom as seen in the [`write_json`](https://github.com/metno/pyaerocom/blob/2dad9c7890096535c9ae4ad23915150e1198ad99/pyaerocom/aeroval/json_utils.py#L72) and [`read_json`](https://github.com/metno/pyaerocom/blob/2dad9c7890096535c9ae4ad23915150e1198ad99/pyaerocom/aeroval/json_utils.py#L54) methods respectively, so I am leaving this as is for now.

Fix json nan-serialization

---

src/aerovaldb/jsondb/jsonfiledb.py
src/aerovaldb/lock/lock.py
src/aerovaldb/utils/__init__.py
src/aerovaldb/utils/asyncio.py
src/aerovaldb/utils/string_utils.py
tests/utils/test_string_utils.py

- A log message will be displayed to indicate if locking is enabled, when initializing a db connection.
- Environment variable `AVDB_USE_LOCKING` now supports giving values in additional formats, including `yes`/`no`.
- API arguments are validated to ensure they don't contain certain characters (which caused files to be stored in the wrong place in some cases) (See #55)
- 
closes #55

Adds log message to indicate locking status, validates parameters and improves environment variable bool parsing.

---

src/aerovaldb/jsondb/jsonfiledb.py

Replaces `pkg_resources` with `importlib.metadata`
`pkg_resources` is not available on newer python versions

Replace deprecated pkg_resources

---

tests/jsondb/test_jsonfiledb.py
tests/test_aerovaldb.py

There were some new tests that were only applied to jsondb (overlay related functionality). This PR fixes that and tests the behaviour for sqlite as well.
NA

Make sqlite fully consistent

---

setup.cfg
src/aerovaldb/aerovaldb.py
src/aerovaldb/jsondb/cache.py
src/aerovaldb/jsondb/jsonfiledb.py

Cache map endpoint (or really all filtered endpoints).
- Filtered endpoints will respect the `cache` argument to getter function calls, and use cached results if `cache=True`.

Cache filtered endpoint

---

conftest.py
setup.cfg
src/aerovaldb/aerovaldb.py
src/aerovaldb/jsondb/cache.py
src/aerovaldb/jsondb/jsonfiledb.py
src/aerovaldb/lock/lock.py
src/aerovaldb/plugins.py
src/aerovaldb/sqlitedb/sqlitedb.py
src/aerovaldb/utils/string_mapper/mapper.py
tests/test_aerovaldb.py

- Removes asyncio option in `aerovaldb.open()`
- Makes timestep mandatory in `AerovalDB.get_contour()`
- Does not break tests in pyaerocom. Probably doesn't break tests in aeroval-api.
- closes #112
- closes #109 
- closes #113

Public API changes for v0.3.0

---

setup.cfg
src/aerovaldb/__init__.py
src/aerovaldb/aerovaldb.py
src/aerovaldb/jsondb/backwards_compatibility.py
src/aerovaldb/jsondb/jsonfiledb.py
src/aerovaldb/sqlitedb/sqlitedb.py
tests/test_aerovaldb.py
tests/test_utils.py

- `QueryEntrys` are cached and are only generated for a file once. Should improve performance of querying significantly.
For the test database with ~50 assets, caching improves querying all assets from 0.026 seconds to 0.003 seconds once the cache has been primed.
- Removed list_glob_stats as its name is misleading. It listed heatmap files. As part of https://github.com/metno/pyaerocom/pull/1529 pyaerocom will use query for this function.
NA

Cache QueryEntries

---

setup.cfg
src/aerovaldb/aerovaldb.py
src/aerovaldb/jsondb/jsonfiledb.py
src/aerovaldb/utils/encode.py

Aerovaldb relies on the cfg_.json file to find the pyaerocom version that wrote a file. When fetching this file to find the version arguments where encoded twice, resulting in attempts to access the wrong file.
NA

Fix double encode when reading config to get pyaerocom version

---

setup.cfg
src/aerovaldb/aerovaldb.py
src/aerovaldb/jsondb/jsonfiledb.py
src/aerovaldb/sqlitedb/sqlitedb.py
tests/test_aerovaldb.py

- Reintroduces `list_glob_stats`.
- Make `list_*` functions return string uri again, instead of `QueryEntry` instances
NA

Reintroduce `list_glob_stats` and ensure backwards compatibility

---

setup.cfg
src/aerovaldb/jsondb/jsonfiledb.py

Fix report issue with `get_report()`.
The introduction of encoding in filenames broke `get_report` as it would try to fetch paths with underscores encoded. This PR, changes `title` to a literal arg as is used for paths, to prevent encoding from being applied. It may be necessary to treat project and experiment as `_LiteralArgs` as well for this endpoint unless we rename the files.
Chat

try fix reports issue

---

src/aerovaldb/aerovaldb.py
src/aerovaldb/jsondb/jsonfiledb.py
tests/jsondb/test_jsonfiledb.py

Fixes issue where underscores would not be encoded properly for the map overlay endpoints. Adds test case that includes underscore.
closes #130

Overlay underscores

---

src/aerovaldb/aerovaldb.py
src/aerovaldb/jsondb/jsonfiledb.py

Fixes issue with encoding being applied to old files, thus being unable to read them. The fix involves trying to read the encoded, and the decoded file path if the former breaks, which isn't pretty, but it works.
The reason for this is that aerovaldb relies on the config file to know which version of pyaerocom wrote the experiment, which is needed to know whether to apply the encoding. Since the cfg file is also potentially encoded, it is at some point necessary to try both to break the cycle.
It may be a good idea to write the version to a different file that is not affected by this, eg a .version file (or this could be a small part of introducing a file index).
closes #128

Fix encoding for old exp

---

setup.cfg
src/aerovaldb/utils/filter.py

Map filtering uses a whitelist of keys to include, which excludes the station_display_name introduced by [this pr](https://github.com/metno/pyaerocom/pull/1634). This includes that key in the whitelist.
NA

Fix missing key
